# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: server
    build: .
    command: gunicorn -b 0.0.0.0:5000 server.wsgi:app
    env_file:
      - ./.flaskenv
      - ./.env
    environment:
      - DATABASE_URI=sqlite:////db/server.db
    volumes:
      - ./server:/code/server
      - ./db/:/db/
    ports:
      - "5000:5000"
