"""make note.location nullable

Revision ID: 07704da313aa
Revises: 320d05cca29e
Create Date: 2023-03-02 11:17:59.260576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07704da313aa'
down_revision = '320d05cca29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
