"""added comments field to notes

Revision ID: 0d3d06eaa384
Revises: f305ebe0af36
Create Date: 2023-02-27 21:26:30.028757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d3d06eaa384'
down_revision = 'f305ebe0af36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', postgresql.ARRAY(sa.String(length=1000)), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
