"""add location to notes

Revision ID: 320d05cca29e
Revises: 8b7771a91e94
Create Date: 2023-03-02 10:56:27.273625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320d05cca29e'
down_revision = '8b7771a91e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
