"""add user_account.root_collection_id

Revision ID: 43067f9db49d
Revises: b41f90b61885
Create Date: 2023-03-02 00:30:01.100847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43067f9db49d'
down_revision = 'b41f90b61885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_collection_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['root_collection_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('root_collection_id')

    # ### end Alembic commands ###
