"""added range data to note

Revision ID: 5aa5fa8257fc
Revises: c65e979c414d
Create Date: 2023-03-02 20:55:20.627388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa5fa8257fc'
down_revision = 'c65e979c414d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_offset', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_offset', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('node_data', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('node_html', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('node_tag_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('node_tag_name')
        batch_op.drop_column('node_html')
        batch_op.drop_column('node_data')
        batch_op.drop_column('end_offset')
        batch_op.drop_column('start_offset')

    # ### end Alembic commands ###
