"""drop note.location

Revision ID: 72742747a8b9
Revises: b5f932505012
Create Date: 2023-02-28 13:52:51.908342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72742747a8b9'
down_revision = 'b5f932505012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('coords', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.TEXT(), autoincrement=False, nullable=False))

    op.drop_table('location')
    # ### end Alembic commands ###
