"""changing notes to varchar

Revision ID: 955fc372068c
Revises: fdc7bd87f309
Create Date: 2023-02-27 17:13:41.951704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955fc372068c'
down_revision = 'fdc7bd87f309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
