"""remove foreign key constraint on user_account.root_collection_id

Revision ID: a27696432d25
Revises: f2831bb915a6
Create Date: 2023-03-02 00:34:37.878968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27696432d25'
down_revision = 'f2831bb915a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_constraint('user_account_root_collection_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.create_foreign_key('user_account_root_collection_id_fkey', 'collection', ['root_collection_id'], ['id'])

    # ### end Alembic commands ###
