"""added reactions and location columns to note

Revision ID: a75435ffe55f
Revises: 0d3d06eaa384
Create Date: 2023-02-27 21:50:34.939118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a75435ffe55f'
down_revision = '0d3d06eaa384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reactions', postgresql.ARRAY(sa.Integer()), nullable=True))
        batch_op.add_column(sa.Column('location', postgresql.JSON(astext_type=sa.Text()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('reactions')

    # ### end Alembic commands ###
