"""add note.location

Revision ID: a793d505b3c3
Revises: 72742747a8b9
Create Date: 2023-02-28 13:53:41.039693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a793d505b3c3'
down_revision = '72742747a8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'location', ['location'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
