"""adding notes to collections

Revision ID: a806d18b726f
Revises: 74f88b945c0d
Create Date: 2023-02-27 15:44:01.759717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a806d18b726f'
down_revision = '74f88b945c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', postgresql.BYTEA(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
