"""remove foreign key constraint from collection.parent_id

Revision ID: aee35610c3ba
Revises: d1062d0f1e8d
Create Date: 2023-03-02 01:10:22.033943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee35610c3ba'
down_revision = 'd1062d0f1e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_constraint('user_account_root_collection_id_key', type_='unique')
        batch_op.drop_column('root_collection_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_collection_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_account_root_collection_id_key', ['root_collection_id'])

    # ### end Alembic commands ###
