"""removing root collection from users

Revision ID: b41f90b61885
Revises: d047b2165245
Create Date: 2023-03-02 00:23:33.328449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41f90b61885'
down_revision = 'd047b2165245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint('note_location_fkey', type_='foreignkey')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('note_location_fkey', 'location', ['location'], ['id'])

    # ### end Alembic commands ###
