"""make usernames non-unique

Revision ID: b634d131cde7
Revises: c10458de5fd9
Create Date: 2023-03-01 14:50:45.588276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b634d131cde7'
down_revision = 'c10458de5fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_constraint('user_account_username_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_account_username_key', ['username'])

    # ### end Alembic commands ###
