"""drop column collections.notes

Revision ID: bb558cdd50c5
Revises: 955fc372068c
Create Date: 2023-02-27 19:10:19.032293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb558cdd50c5'
down_revision = '955fc372068c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
