"""allow note.location nullable

Revision ID: c10458de5fd9
Revises: a793d505b3c3
Create Date: 2023-02-28 14:05:26.601816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10458de5fd9'
down_revision = 'a793d505b3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
