"""merge location into note

Revision ID: c65e979c414d
Revises: 07704da313aa
Create Date: 2023-03-02 12:54:08.202670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65e979c414d'
down_revision = '07704da313aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_type', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('url', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('x', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('y', sa.Integer(), nullable=False))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('y')
        batch_op.drop_column('x')
        batch_op.drop_column('url')
        batch_op.drop_column('location_type')

    op.create_table('location',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name='location_note_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name='location_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='location_pkey')
    )
    # ### end Alembic commands ###
