"""changed collection.parent_id

Revision ID: d1062d0f1e8d
Revises: d68645c1c0ab
Create Date: 2023-03-02 00:45:05.136294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1062d0f1e8d'
down_revision = 'd68645c1c0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'collection', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
