"""remove foreign key constraint from collection.parent_id

Revision ID: d68645c1c0ab
Revises: a27696432d25
Create Date: 2023-03-02 00:39:18.140220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68645c1c0ab'
down_revision = 'a27696432d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint('collection_parent_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_foreign_key('collection_parent_id_fkey', 'collection', ['parent_id'], ['id'])

    # ### end Alembic commands ###
