"""change notes column type to text

Revision ID: fdc7bd87f309
Revises: a806d18b726f
Create Date: 2023-02-27 16:38:58.420825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdc7bd87f309'
down_revision = 'a806d18b726f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=postgresql.BYTEA(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
